### ISSUE TITLE
Question about udp packets to loxone server

### ISSUE THREAD

**Issue by Mac5000** [marcelschreiner/hue-to-loxone#1]
Hi,

First of all thank you for posting this script.    I've got it working today and I see all events being listed on my linux machine.
The script is sending the UDP packets to Loxone however in Loxone I'm not receiving all the information of the event.

For example :   on my linux machine I see this event output 

received event update LightLevel(id='61954f6b-e89f-4741-85ce-f0c30aee2788', owner=ResourceIdentifier(rid='cb58b3b2-cfcd-4e14-ab17-a8cff89325d3', rtype=<ResourceTypes.DEVICE: 'device'>), enabled=True, light=LightLevelFeature(light_level_report=LightLevelReport(changed=datetime.datetime(2023, 10, 29, 14, 31, 8, 296000, tzinfo=datetime.timezone.utc), light_level=4825), light_level=4825, light_level_valid=True), id_v1='/sensors/40', type=<ResourceTypes.LIGHT_LEVEL: 'light_level'>)
EVENT: {event}

However in Loxone I'm only getting ;

15;15:32:37.043;Loxone Miniserver;Received;10.10.4.41;Philips Hue;5000;hue_event{sensor_id}/{sensor_state};68 75 65 5f 65 76 65 6e 74 7b 73 65 6e 73 6f 72 5f 69 64 7d 2f 7b 73 65 6e 73 6f 72 5f 73 74 61 74 65 7d;;

But the objects field remains empty ...

Do you have any idea what could be the problem ?

**Comment by marcelschreiner** [comment]
Hello @Mac5000 

Happy to hear, that someone out there in the internet has found some use in my script. 😇

I did some tests on my end and I was able to figure out the issue.
When using pylint I formatted the strings wrong and did not test it again (I forgot the f in front of the formatted strings). 

```python
age = 30
message = "You are {age} years old"
print(message)
```
would have returned "You are {age} years old"

instead of...

```python
age = 30
message = f"You are {age} years old"
print(message)
```
"You are 30 years old"

Sorry for any inconveniences caused by my little fault. I hope the fix in the latest commit 97d64e2 works for you.

**Comment by Mac5000** [comment]
Hi, thank you so much for the quick fix.   Now I'm receiving the correct messages.

**Comment by Mac5000** [comment]
Hi, Just to let you know I have also changed the udp message to this : 

if sensor_id != "":
        event = f"hue_event{sensor_id}/{item.type.name}/{sensor_state}"

As without the item.type.name you receive a udp message with just the sensor ID and a value but you have no idea what event type it is.    Now it is also sending the event type so I can filter and create actions for specific event type ID's
