### ISSUE TITLE
Receive Hue bridge group events

### ISSUE THREAD

**Issue by Mac5000** [marcelschreiner/hue-to-loxone#2]
Hi,

I see that the aiohue library also contains all necessary syntax regarding Hue light groups and I've been looking how this could be integrated in your code but my knowledge is not enought to find a solution.

What I'm looking for is to get a event when a group is turned on or (True or false in Hue).     Then I can use this value in a virtual input and update the status of the on/off switch in Loxone whenever a light group is turning on or off.

As I'm using Hue automation with light sensors, groups are being turned off automatically after x minutes.   For the moment I receive the event when motion is triggered and so the group is turned on, but when the timer expires it's the Hue bridge that switches the light group off so that event is not being reported leaving the button in Loxone in the ON state while the group is no longer in the ON state.

Is this something you could add to the script ?

Kind regards,

Filip

**Comment by marcelschreiner** [comment]
Hey Filip,

Thanks for the detailed info! I totally get why you'd want the Loxone status to match up with the Hue light groups.

Good news - I've tweaked the script to handle on/off events for groups. Now it should keep your Loxone status in sync with the Hue light groups.

Grab the latest version of the code and give it a spin. Let me know how it goes!

(Note I made two commits. [d6cb006](https://github.com/marcelschreiner/hue-to-loxone/commit/d6cb006f29e72dc6d8632a6306840a05e8dda46c) fixes some linter issues that snuck in my first commit)

Cheers,
Marcel

**Comment by Mac5000** [comment]
Hi Marcel,

Thanks for getting back to me so fast.   I'll give it a try tomorrow and let you know !

Kind regards,

Filip

**Comment by Mac5000** [comment]
Hi Marcel,

Just tested the new version of your script and it works like a charm.    Thanks again for you fast response and helping me out.

Nothing but kudo's to you.

Kind regards,

Filip

**Comment by marcelschreiner** [comment]
Hi Filip,

Happy to hear that I was able to solve your problem ✌🏼🙌🏼

Happy automating,
Marcel
